spring:
  datasource:
    url: jdbc:sqlserver://${LOCAL_HOST};database=${DATABASE_NAME};encrypt=true;trustServerCertificate=true;
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2019Dialect
    show-sql: false
    ddl-auto: update
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  security:
    user:
      name: sa
      password: 123
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

JWT_SECRET: ${JWT_SECRET}
twilio:
  account_id: ACac9cf2473f96b1ddbf8ed4212c58855e
  auth_token: 714ccbb6be7aa7c1296f58490f1f8e8b
  trial_number: +14407502078
