management:
  endpoints:
    web:
      exposure:
        include: '*'
    info:
      env:
        enabled: true
  info:
    application:
      name: e-world
      description: E-commerce online
      author: Tan Dat
      version: '@project.version@'
  spring:
    profiles:
      active: ${SPRING_PROFILES_ACTIVE}